### ISSUE TITLE
Suggestion: Change code screenshots for actual code

### ISSUE THREAD

**Issue by mattaereal** [obheda12/Solidity-Security-Compendium#1]
Hi, and thanks for this repo. I was looking for something more updated than the SWC Registry and stumbled upon this.

Would you mind changing the screenshot examples for real code?

**Comment by obheda12** [comment]
Hi I plan to do QoL changes such as this in the future!.

**Comment by mattaereal** [comment]
Let me know if you need any help! I might be able to lend you a hand
